name: Release
on:
  release:
    types: [created]
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      # Checkout the exact commit tagged on the release.
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.release.target_commitish }}

      # This is the action in this repo! 👇
      # Note we set an `id` called `release`. We'll use that later...
      - name: Validate and extract release information
        id: release
        uses: manovotny/github-releases-for-automated-package-publishing-action@v2.0.1

      # When setting the node version for publishing a release, it's also impotant
      # to set `always-auth` and `registry-url` too. I've encountered vauge errors
      # and publishing doesn't work unless they are supplied.
      #
      # This example is using NPM's registry. If you were publishing to GitHub's
      # Package registry, you'd use `https://npm.pkg.github.com` instead.
      - name: Set node version
        uses: actions/setup-node@v3
        with:
          always-auth: true
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'

      # This will publish a version of a package.
      - name: Publish version
        if: steps.release.outputs.tag == ''
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

      - name: Publish tagged version
        if: steps.release.outputs.tag != ''
        run: npm publish --tag ${{ steps.release.outputs.tag }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}